ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "boq" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "designer_allowlist" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "floor_plans" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "meeting_minutes" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "moodboards" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "object_assets" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "project_clients" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "project_schedules" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "project_vendors" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "quote_files" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "quote_templates" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "saved_assets" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "sops" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "specifications" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "task_alerts" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "task_dependencies" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "user_project_assignments" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "user_roles" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "vendor_categories" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "vendor_contacts" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "vendor_invoices" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "vendors" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "works_order_items" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "works_order_templates" ADD COLUMN IF NOT EXISTS "org_id" varchar;--> statement-breakpoint
ALTER TABLE "works_orders" ADD COLUMN IF NOT EXISTS "org_id" varchar;